const UserInfo = [
  {
    userType: "Rider",
    fullName: "Teejay Teko",
    email: "example.com@gmail.com",
    number: "08064838405",
    ridesCompleted: 657,
    location: "Lagos",
    status: "Active",
  },
  {
    userType: "driver",
    fullName: "teejay teko",
    email: "johndoe@gmail.com",
    number: "08012345678",
    ridesCompleted: 432,
    location: "lagos",
    status: "Inactive",
  },
  {
    userType: "Rider",
    fullName: "teejay teko",
    email: "janesmith@gmail.com",
    number: "08098765432",
    ridesCompleted: 890,
    location: "lagos",
    status: "Active",
  },
  {
    userType: "Rider",
    fullName: "teejay teko",
    email: "michaelj@gmail.com",
    number: "08123456789",
    ridesCompleted: 120,
    location: "lagos",
    status: "Active",
  },
  {
    userType: "Rider",
    fullName: "teejay teko",
    email: "sarahwilliams@gmail.com",
    number: "08187654321",
    ridesCompleted: 345,
    location: "lagos",
    status: "Inactive",
  },
  {
    userType: "Rider",
    fullName: "teejay teko",
    email: "davidbrown@gmail.com",
    number: "08034567890",
    ridesCompleted: 765,
    location: "lagos",
    status: "Active",
  },
  {
    userType: "driver",
    fullName: "teejay teko",
    email: "emilydavis@gmail.com",
    number: "08067890123",
    ridesCompleted: 234,
    location: "lagos",
    status: "Active",
  },
  {
    userType: "Rider",
    fullName: "teejay teko",
    email: "chriswilson@gmail.com",
    number: "08109876543",
    ridesCompleted: 543,
    location: "lagos",
    status: "Inactive",
  },
  {
    userType: "Rider",
    fullName: "teejay teko",
    email: "oliviamartinez@gmail.com",
    number: "08023456789",
    ridesCompleted: 876,
    location: "lagos",
    status: "suspend",
  },
  {
    userType: "Rider",
    fullName: "teejay teko",
    email: "danielanderson@gmail.com",
    number: "08045678901",
    ridesCompleted: 678,
    location: "lagos",
    status: "Active",
  },
];

export default UserInfo;
